### ISSUE TITLE
Invert logical operators

### ISSUE THREAD

**Issue by k3rn31** [go-gremlins/gremlins#137]
This is a token mutator that should:

| Orig | Mutation |
|-----|----------|
| `&&` | `\|\|` |
| `\|\|` | `&&` |

INVERT_LOGICAL

Edit: `!` mutator has been moved to a separate issue (#145) because it requires a more complex work on the mutator engine.

| Orig| Mutation| 
|-----|------|
| `!` | `!!` |

**Comment by vsvastey** [comment]
I'd like to take care of that

**Comment by vsvastey** [comment]
@k3rn31  Should this mutator be enabled by default?

**Comment by k3rn31** [comment]
Hi @vsvastey,
you're welcome!

I would say no, let's keep it disabled by default, at least for now. In the future I'd make some statistics on which MutantTypes are more effective/important to test and on that basis we can make the default set better.

**Comment by k3rn31** [comment]
@vsvastey, regarding the last mutation (`!` to `!!`), it can be tricky to implement in the current engine since it is a unary that should be wrapped in another unary. This is something the current engine doesn't do. It is not a simple token swap like all the others.
Alternatively we could simply remove the `!` (we should have the same result). But in this case as well, it is not a token swap.

If you have ideas on how to do that elegantly and in a reusable way, let's discuss about that. If this turns out to be too complicated, we can remove it from this issue and immediately create another one to track its addition later on.

**Comment by vsvastey** [comment]
@k3rn31 Yeah, I would prefer to implement a simple case first, and then get back to `!` -> `!!`.
Would you please file it as a dedicated ticket?
Please feel free to assign it to me, it's an interesting case I'd like to think about.
