### ISSUE TITLE
Bitwise operator replacement

### ISSUE THREAD

**Issue by k3rn31** [go-gremlins/gremlins#138]
Invert bitwise operators.

| From | To |
| -- | -- |
| `&` | `\|` |
| `\|` | `&` |
| `^` | `&` |
| `&^` | `&` |
| `»` | `«` |
| `«` | `»` |

INVERT_BITWISE

Disabled by default

**Comment by alessio-perugini** [comment]
@k3rn31 If you don't mind I'd like to take this.

How do we want to handle the bitwise ops assignments?
- Do we want to add them under the `INVERT_ASSIGNMENTS` mutator?
- Or do we want to create a more specific mutator like `INVERT_BITWISE_ASSIGNMENTS`?
```
AND_ASSIGN:     "&=",
OR_ASSIGN:      "|=",
XOR_ASSIGN:     "^=",
SHL_ASSIGN:     "<<=",
SHR_ASSIGN:     ">>=",
AND_NOT_ASSIGN: "&^=",
```

**Comment by k3rn31** [comment]
Hello,
please, go ahead! 
What do you think of calling it `INVERT_BITWISE`?

Let's keep it disabled by default.

**Comment by alessio-perugini** [comment]
@k3rn31 great. I've opened #169 to track the bitwise assignments 😄

**Comment by k3rn31** [comment]
This has been completed but for some reason it wasn't closed with the merge.
