### ISSUE TITLE
Add a flag --coverpkg, handed over to "go test -cover"

### ISSUE THREAD

**Issue by hknutzen** [go-gremlins/gremlins#162]
# 🚀 Feature Request

### Is your feature request related to a problem? Please describe

Gremlins determines the test coverage of a project, before applying mutations.
My project https://github.com/hknutzen/Netspoc has only integration tests, no unit tests.
Test coverage of this project is determined with this command:
`go test -coverpkg ./pkg/...`

Gremlins currently doesn't know about flag `-coverpkg` and hence all code lines are marked as "NOT COVERED".
### Describe the solution you'd like

Add a flag `--coverpkg` to the unleash command that is handed over to the call of `go test -cover`, similar to flag `--tags`.
### Describe alternatives you've considered

I am not aware of any alternatives.

### Additional context

From the output of `go help testflag`:
>         -coverpkg pattern1,pattern2,pattern3
>             Apply coverage analysis in each test to packages matching the patterns.
>             The default is for each test to analyze only the package being tested.
>             See 'go help packages' for a description of package patterns.
>             Sets -cover.

**Comment by k3rn31** [comment]
Hello, thanks for the feature request. I agree we need this feature, I'll put for 0.5.0 milestone for now, but let's see if we can squeeze it in 0.4.0 (since it is taking longer than anticipated anyway).
We need to analyze the impacts of this flag to the current package scanning behaviour, I believe there could be some corner cases to consider.

**Comment by hknutzen** [comment]
The patched version from my pull request works fine for my project.
I call it like this in directory Netspoc/go:
`gremlins run -i --coverpkg ./pkg/...`
It is still running. 
About 90% of the mutations get KILLED.
It will be very interesting to investigate the LIVED mutations.

**Comment by k3rn31** [comment]
That's good! We'll review the PR soon and merge it.
