### ISSUE TITLE
Use comma separated value for -tags in test

### ISSUE THREAD

**Issue by hknutzen** [go-gremlins/gremlins#165]
In https://github.com/go-gremlins/gremlins/blob/ec07e489fffbb98f5ca74109b3e680fb1c5a04a9/internal/coverage/coverage_test.go#L77
the value for flag "-tag" is given as "tag1 tag2".
But according to documentation, this should be written as "tag1,tag2".
From `go help build`:
>         -tags tag,list
>                 a comma-separated list of build tags to consider satisfied during the
>                 build. For more information about build tags, see the description of
>                 build constraints in the documentation for the go/build package.
>                 (Earlier versions of Go used a space-separated list, and that form
>                 is deprecated but still recognized.)

**Comment by k3rn31** [comment]
This is a test "issue". The test will receive the tags exactly as provided by the flag. If you pass tests comma separated, they will be comma separated in the go test command.
It has been done like so to support also older versions of Go where tags where space separated.
We can certainly change the test to make this more explicit, but I'd still support both formats.
