### ISSUE TITLE
Wrong name of test case in coverage_test.go

### ISSUE THREAD

**Issue by hknutzen** [go-gremlins/gremlins#166]
Two test case have the same name "from root, integration mode":
https://github.com/go-gremlins/gremlins/blob/ec07e489fffbb98f5ca74109b3e680fb1c5a04a9/internal/coverage/coverage_test.go#L61-L72
I think the second test should have name "from folder, integration mode".

**Comment by k3rn31** [comment]
Yes, definitely a mistake here.

**Comment by fahimbagar** [comment]
Hi @k3rn31, first-time contributor here :raised_back_of_hand:.
I hope you don't mind if I push the PR ahead since I've seen it as `v0.5.0` milestone.

Thanks for the repo.
