### ISSUE TITLE
When a TIMED OUT occur we do not clean the go-build* folder in /tmp

### ISSUE THREAD

**Issue by alessio-perugini** [go-gremlins/gremlins#182]
When we call the `go test` it first builds all the files needed to run the tests. The build artifacts are created under /tmp dir by default and have a name like `go-build19625282`. 

Every time we kill the execution of `go test` it does not clean the build directory created under the /tmp dir. This means that every time we have a mutation that goes on TIMED_OUT we do not clear the relative build dirs.

Step I did to reproduce:

1. rm -rf /tmp/go-build*
2. gremlin unleash | grep "TIMED OUT" | wc -l
3. ls /tmp | grep go-build | wc -l

## Solution

Set the `GOTMPDIR` env var that will be used by `go test` to store all the build dirs of gremlins. Clean up that folder before quitting `gremlins`.

**Comment by k3rn31** [comment]
This is almost the same as #177, and both the solution proposed are analogous. Maybe it is worth to implement them together. What do you think?

**Comment by alessio-perugini** [comment]
@k3rn31 Actually yes we can implement both in the same PR.
From go doc:
>By default, the go tool creates its temporary files and directories in the system temporary directory (for example, $TMPDIR on Unix). If the new environment variable $GOTMPDIR is set, the go tool will create its temporary files and directories in that directory instead.

if you only export the GOCACHE go test still creates go-build dirs in the /tmp folder. So changing the GOTMPDIR will move those folders in whatever dir we choose.

I did a quick test from the terminal:
Using `GOCACHE`
```bash
export GOCACHE=/tmp/gremlins 
./dist/bin/gremlins unleash .
```
When we have a timed_out we still have go-build folder in /tmp.

Using `GOTMPDIR`
```bash
export GOTMPDIR=/tmp/gremlins
./dist/bin/gremlins unleash .
```
If we go under /tmp/gremlins we can find the go-build dirs there.

**Comment by alessio-perugini** [comment]
@k3rn31 You can find my idea here: https://github.com/alessio-perugini/gremlins/pull/3/files
But I'm stuck because it seems to not work. Every mutation gets killed and I suspect we don't even build and run them because the total time is 387ms 🤔

**Comment by k3rn31** [comment]
@alessio-perugini I did, more or less, the same experiment yesterday with the same result, everything KILLED... I don't know why 😄 
I was trying to understand how to implement #177.

**Comment by alessio-perugini** [comment]
@k3rn31 using `os.Setenv("GOTMPDIR", filepath.Dir(rootDir))` seems to work fine. :exploding_head: 

```go
func (m *mutantExecutor) Start(w *workerpool.Worker) {
	defer m.wg.Done()
	workerName := fmt.Sprintf("%s-%d", w.Name, w.ID)
	rootDir, err := m.wdDealer.Get(workerName)
	if err != nil {
		panic("error, this is temporary")
	}

	os.Setenv("GOTMPDIR", filepath.Dir(rootDir))
     ...
```

**Comment by k3rn31** [comment]
I believe you have to execute
```go
cmd.Env = os.Environ()
```
before setting the GOTMPDIR variable, otherwise you will lose the current env (only GOTMPDIR will be present).

```
cmd.Env = os.Environ()
cmd.Env = append(cmd.Env, m.goTmpDirEnv)
```

**Comment by alessio-perugini** [comment]
@k3rn31 How I couldn't think about that! Your suggestion is working flawlessly :star_struck:
