### ISSUE TITLE
Can we please add a feature to only run mutation tests on certain files [request] 

### ISSUE THREAD

**Issue by srazzell** [go-gremlins/gremlins#193]
# 🚀 Feature Request

### Is your feature request related to a problem? Please describe
None

### Describe the solution you'd like
I'd really love a command line option such as --paths-to-mutate or --files-to-mutate where we only run on a subset of the files in a repo instead of running on every file. You pass in a comma separated list of files and those are the only files that are mutated.

### Describe alternatives you've considered
Using a different go mutations library

### Additional context
I'd like to run gremlins on the files changed in a pull request, so that gremlins can be used on larger repos.

Examples from other mutation libraries:  
https://github.com/muter-mutation-testing/muter
https://github.com/avito-tech/go-mutesting#how-do-i-use-go-mutesting

**Comment by k3rn31** [comment]
Hi @srazzell, thank you for the feature request!
Maybe, the feature you are requesting already exists.
Could the recently added `--coverpkg` be enough for the purpose? https://gremlins.dev/0.4/usage/commands/unleash/#cover-packages

**Comment by srazzell** [comment]
I'm looking for a way to only mutate some of the files instead of all the files in a repo. I read the docs and `--coverpkg` doesn't sound like it does that, but correct me if I'm wrong.

**Comment by k3rn31** [comment]
Ok, I believe we can plan this feature.

**Comment by rusinikita** [comment]
@srazzell Can you please check if it solves your problem #215
