### ISSUE TITLE
[request] only generate mutants in paths that cover changed code

### ISSUE THREAD

**Issue by SOF3** [go-gremlins/gremlins#214]
# 🚀 Feature Request

### Is your feature request related to a problem? Please describe

For projects with low test coverage baseline, it is a common <sup>[citation needed]</sup> practice to enforce only diff coverage rather than full coverage. Mutation testing would be useful to ensure that new tests have sufficient assertions, but its impact is largely diluted by the large amount of unrelated code.

### Describe the solution you'd like

During the initial passing run, identify the lines covered by unit tests that cover changed files/lines. When generating mutants, only generate them on these covered lines.

### Describe alternatives you've considered

Alternatively, only generate mutants on changed lines to further reduce dilution.

**Comment by rusinikita** [comment]
@k3rn31 Hi! I'd like to make PR on this issue. And already have a draft, because i needed that for my project

**Comment by rusinikita** [comment]
Sorry, I have not seen this issue when decided to try make change.

Here is PR. Take a look, please.

https://github.com/go-gremlins/gremlins/pull/215
