### ISSUE TITLE
Add support for a configuration file

### ISSUE THREAD

**Issue by k3rn31** [go-gremlins/gremlins#31]
Gremlins should be configurable with a configuration file, for example in the root of the project being tested. 

A file named `.gremlins.yml` can live at 
- the root of the go module analysed (`./.gremlins.yml`)
- at the `$HOME/.config/gremlins/gremlins.yml`
- at `$HOME/.gremlins.yml`

If the file is not found, it will use sensible defaults. It should be possible to override the position of the config file with a flag.
Flag: `--config-file filename`/`-cf filename`

Using [Viper](https://github.com/spf13/viper) could be a good idea.

**Comment by vmarchese** [comment]
I'd like to work on this

**Comment by k3rn31** [comment]
Hi @vmarchese, thanks, it is assigned to you.

**Comment by vmarchese** [comment]
To make the configuration flexible and expandable to different subsections (i.e. run, mutators, tags,...) I will add a package `pkg/configuration` with a struct inside as follows (more or less ;) ): 

```go
package configuration

type GremlinsCfg struct{
    DryRun bool
    Tags []string

   // this can be expanded and/or reorganized
}


func (c *GremlinsCfg) FromFlags(cmd *cobra.Command){
	cmd.Flags().BoolVarP(&c.DryRun, "dry-run", "d", false, "find mutations but do not executes tests")
	cmd.Flags().StringVarP(&c.BuildTags, "tags", "t", "", "a comma-separated list of build tags")
}

```

Then I will add to the unleash command the viper initialization and hierarchical setting and binding of the flags, i.e.:

config file -> env vars -> flags

**Comment by k3rn31** [comment]
@vmarchese just as a note, consider that Viper tags can be bound to Cobra flags, so most probably it is not necessary to use the Tags[] in the struct if you use Viper.
Check it here: https://cobra.dev/

**Comment by vmarchese** [comment]
Yep, by `Tags` I meant go build tags that can be treated as a string (as in the go command). 
AFAIK Viper doesn't manage the override of the flags but it must be done manually but I'll check better :)

**Comment by k3rn31** [comment]
Thanks. Just to be clear with the intent, by override I intend that the flag takes precedence on the config file, so is the flag that overrides.
